name: Deploy to Salesforce

on:
  push:
    branches:
      - main  # Or your deployment branch

jobs:
  deploy:
    runs-on: windows-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Install Salesforce CLI
        run: |
          npm install sfdx-cli --global

      - name: Authenticate with JWT
        run: |
          echo "${{ secrets.SF_JWT_KEY }}" > server.key
          name: Authenticate to Salesforce
        run: |
        sfdx auth:jwt:grant --username ${{ secrets.SF_USERNAME }} --clientid ${{ secrets.SF_CLIENT_ID }} --jwtkeyfile server.key --instanceurl ${{ secrets.SF_LOGIN_URL }} --setdefaultusername

      - name: Deploy metadata
        run: |
          sfdx force:source:deploy -p force-app -u ${{ secrets.SF_USERNAME }} --wait 10 --verbose
